//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BieuDoTheoDoi
    {
        public int id { get; set; }
        public int idTaiKhoan { get; set; }
        public int Thu2 { get; set; }
        public int Thu3 { get; set; }
        public int Thu4 { get; set; }
        public int Thu5 { get; set; }
        public int Thu6 { get; set; }
        public int Thu7 { get; set; }
        public int ChuNhat { get; set; }
        public System.DateTime NgayBatDau { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
