//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WebLapTrinhEntities : DbContext
    {
        public WebLapTrinhEntities()
            : base("name=WebLapTrinhEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BieuDoTheoDoi> BieuDoTheoDois { get; set; }
        public virtual DbSet<CapDo> CapDoes { get; set; }
        public virtual DbSet<DSBaiHoc> DSBaiHocs { get; set; }
        public virtual DbSet<DSBaiHocPass_Of_TaiKhoan> DSBaiHocPass_Of_TaiKhoan { get; set; }
        public virtual DbSet<DSBanBe> DSBanBes { get; set; }
        public virtual DbSet<DSCauHoi> DSCauHois { get; set; }
        public virtual DbSet<DSDapAn> DSDapAns { get; set; }
        public virtual DbSet<DSKhoaHocPass_Of_TaiKhoan> DSKhoaHocPass_Of_TaiKhoan { get; set; }
        public virtual DbSet<DSThongBao> DSThongBaos { get; set; }
        public virtual DbSet<DSYeuCauKetBan> DSYeuCauKetBans { get; set; }
        public virtual DbSet<KhoaHoc> KhoaHocs { get; set; }
        public virtual DbSet<LoaiDiemKN> LoaiDiemKNs { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<ThongTinTaiKhoan> ThongTinTaiKhoans { get; set; }
    
        public virtual ObjectResult<ACCOUNT_LOGIN_Result> ACCOUNT_LOGIN(string user, string pass)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ACCOUNT_LOGIN_Result>("ACCOUNT_LOGIN", userParameter, passParameter);
        }
    
        public virtual ObjectResult<GET_BieuDoTheoDoi_Result> GET_BieuDoTheoDoi(Nullable<int> idTaikhoan)
        {
            var idTaikhoanParameter = idTaikhoan.HasValue ?
                new ObjectParameter("idTaikhoan", idTaikhoan) :
                new ObjectParameter("idTaikhoan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_BieuDoTheoDoi_Result>("GET_BieuDoTheoDoi", idTaikhoanParameter);
        }
    
        public virtual ObjectResult<Get_CapDo_Result> Get_CapDo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_CapDo_Result>("Get_CapDo");
        }
    
        public virtual ObjectResult<Get_DSBaiHoc_ById_Result> Get_DSBaiHoc_ById(Nullable<int> idKhoaHoc)
        {
            var idKhoaHocParameter = idKhoaHoc.HasValue ?
                new ObjectParameter("idKhoaHoc", idKhoaHoc) :
                new ObjectParameter("idKhoaHoc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_DSBaiHoc_ById_Result>("Get_DSBaiHoc_ById", idKhoaHocParameter);
        }
    
        public virtual ObjectResult<GET_DSCauHoi_Follow_IdBaiHoc_IdCapDo_Result> GET_DSCauHoi_Follow_IdBaiHoc_IdCapDo(Nullable<int> idBaiHoc, Nullable<int> idCapDo)
        {
            var idBaiHocParameter = idBaiHoc.HasValue ?
                new ObjectParameter("idBaiHoc", idBaiHoc) :
                new ObjectParameter("idBaiHoc", typeof(int));
    
            var idCapDoParameter = idCapDo.HasValue ?
                new ObjectParameter("idCapDo", idCapDo) :
                new ObjectParameter("idCapDo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_DSCauHoi_Follow_IdBaiHoc_IdCapDo_Result>("GET_DSCauHoi_Follow_IdBaiHoc_IdCapDo", idBaiHocParameter, idCapDoParameter);
        }
    
        public virtual ObjectResult<GET_DSDapAn_Follow_IdBaiHoc_IdCapDo_Result> GET_DSDapAn_Follow_IdBaiHoc_IdCapDo(Nullable<int> idBaiHoc, Nullable<int> idCapDo)
        {
            var idBaiHocParameter = idBaiHoc.HasValue ?
                new ObjectParameter("idBaiHoc", idBaiHoc) :
                new ObjectParameter("idBaiHoc", typeof(int));
    
            var idCapDoParameter = idCapDo.HasValue ?
                new ObjectParameter("idCapDo", idCapDo) :
                new ObjectParameter("idCapDo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_DSDapAn_Follow_IdBaiHoc_IdCapDo_Result>("GET_DSDapAn_Follow_IdBaiHoc_IdCapDo", idBaiHocParameter, idCapDoParameter);
        }
    
        public virtual ObjectResult<Get_DSKhoaHoc_Result> Get_DSKhoaHoc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_DSKhoaHoc_Result>("Get_DSKhoaHoc");
        }
    
        public virtual ObjectResult<GET_DSKhoaHocPass_By_IdTTTaiKhoan_Result> GET_DSKhoaHocPass_By_IdTTTaiKhoan(Nullable<int> idTTTaiKhoan)
        {
            var idTTTaiKhoanParameter = idTTTaiKhoan.HasValue ?
                new ObjectParameter("idTTTaiKhoan", idTTTaiKhoan) :
                new ObjectParameter("idTTTaiKhoan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_DSKhoaHocPass_By_IdTTTaiKhoan_Result>("GET_DSKhoaHocPass_By_IdTTTaiKhoan", idTTTaiKhoanParameter);
        }
    
        public virtual ObjectResult<GET_DSThongBao_Result> GET_DSThongBao(Nullable<int> idaccount)
        {
            var idaccountParameter = idaccount.HasValue ?
                new ObjectParameter("idaccount", idaccount) :
                new ObjectParameter("idaccount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_DSThongBao_Result>("GET_DSThongBao", idaccountParameter);
        }
    
        public virtual ObjectResult<Get_LoaiDiemKinhNghiem_Result> Get_LoaiDiemKinhNghiem()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_LoaiDiemKinhNghiem_Result>("Get_LoaiDiemKinhNghiem");
        }
    
        public virtual ObjectResult<GET_THONGTINTAIKHOAN_Result> GET_THONGTINTAIKHOAN(Nullable<int> idTaikhoan)
        {
            var idTaikhoanParameter = idTaikhoan.HasValue ?
                new ObjectParameter("idTaikhoan", idTaikhoan) :
                new ObjectParameter("idTaikhoan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_THONGTINTAIKHOAN_Result>("GET_THONGTINTAIKHOAN", idTaikhoanParameter);
        }
    
        public virtual int INSERT_ACCOUNT(string user, string pass)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_ACCOUNT", userParameter, passParameter);
        }
    
        public virtual int THEM_THONGTINTAIKHOAN(Nullable<int> idkhoahoc, Nullable<int> idcapdo, Nullable<int> diemKN, Nullable<int> diemKNDay, Nullable<int> idtaikhoan, string ngayhoc)
        {
            var idkhoahocParameter = idkhoahoc.HasValue ?
                new ObjectParameter("idkhoahoc", idkhoahoc) :
                new ObjectParameter("idkhoahoc", typeof(int));
    
            var idcapdoParameter = idcapdo.HasValue ?
                new ObjectParameter("idcapdo", idcapdo) :
                new ObjectParameter("idcapdo", typeof(int));
    
            var diemKNParameter = diemKN.HasValue ?
                new ObjectParameter("diemKN", diemKN) :
                new ObjectParameter("diemKN", typeof(int));
    
            var diemKNDayParameter = diemKNDay.HasValue ?
                new ObjectParameter("diemKNDay", diemKNDay) :
                new ObjectParameter("diemKNDay", typeof(int));
    
            var idtaikhoanParameter = idtaikhoan.HasValue ?
                new ObjectParameter("idtaikhoan", idtaikhoan) :
                new ObjectParameter("idtaikhoan", typeof(int));
    
            var ngayhocParameter = ngayhoc != null ?
                new ObjectParameter("ngayhoc", ngayhoc) :
                new ObjectParameter("ngayhoc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("THEM_THONGTINTAIKHOAN", idkhoahocParameter, idcapdoParameter, diemKNParameter, diemKNDayParameter, idtaikhoanParameter, ngayhocParameter);
        }
    
        public virtual int UPDATE_DSThongBao_Follow_Id_IdAccount(Nullable<int> id, Nullable<int> idAccount)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var idAccountParameter = idAccount.HasValue ?
                new ObjectParameter("idAccount", idAccount) :
                new ObjectParameter("idAccount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_DSThongBao_Follow_Id_IdAccount", idParameter, idAccountParameter);
        }
    
        public virtual int Update_PassWord_Account(string username, string currentPass, string newPass)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var currentPassParameter = currentPass != null ?
                new ObjectParameter("currentPass", currentPass) :
                new ObjectParameter("currentPass", typeof(string));
    
            var newPassParameter = newPass != null ?
                new ObjectParameter("newPass", newPass) :
                new ObjectParameter("newPass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_PassWord_Account", usernameParameter, currentPassParameter, newPassParameter);
        }
    
        public virtual ObjectResult<Get_all_account_same_khoahoc_Result> Get_all_account_same_khoahoc(Nullable<int> idTaiKhoan, Nullable<int> idKhoaHoc)
        {
            var idTaiKhoanParameter = idTaiKhoan.HasValue ?
                new ObjectParameter("idTaiKhoan", idTaiKhoan) :
                new ObjectParameter("idTaiKhoan", typeof(int));
    
            var idKhoaHocParameter = idKhoaHoc.HasValue ?
                new ObjectParameter("idKhoaHoc", idKhoaHoc) :
                new ObjectParameter("idKhoaHoc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_all_account_same_khoahoc_Result>("Get_all_account_same_khoahoc", idTaiKhoanParameter, idKhoaHocParameter);
        }
    
        public virtual int ThemBaiHocPass(Nullable<int> idTTTaiKhoan, Nullable<int> idBaiHoc)
        {
            var idTTTaiKhoanParameter = idTTTaiKhoan.HasValue ?
                new ObjectParameter("idTTTaiKhoan", idTTTaiKhoan) :
                new ObjectParameter("idTTTaiKhoan", typeof(int));
    
            var idBaiHocParameter = idBaiHoc.HasValue ?
                new ObjectParameter("idBaiHoc", idBaiHoc) :
                new ObjectParameter("idBaiHoc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemBaiHocPass", idTTTaiKhoanParameter, idBaiHocParameter);
        }
    }
}
