//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WebLapTrinhEntities : DbContext
    {
        public WebLapTrinhEntities()
            : base("name=WebLapTrinhEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CapDo> CapDoes { get; set; }
        public virtual DbSet<DSBaiHoc> DSBaiHocs { get; set; }
        public virtual DbSet<DSBanBe> DSBanBes { get; set; }
        public virtual DbSet<DSCauHoi> DSCauHois { get; set; }
        public virtual DbSet<DSDapAn> DSDapAns { get; set; }
        public virtual DbSet<DSThongBao> DSThongBaos { get; set; }
        public virtual DbSet<DSYeuCauKetBan> DSYeuCauKetBans { get; set; }
        public virtual DbSet<KhoaHoc> KhoaHocs { get; set; }
        public virtual DbSet<LoaiDiemKN> LoaiDiemKNs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<ThongTinTaiKhoan> ThongTinTaiKhoans { get; set; }
    
        public virtual ObjectResult<ACCOUNT_LOGIN_Result> ACCOUNT_LOGIN(string user, string pass)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ACCOUNT_LOGIN_Result>("ACCOUNT_LOGIN", userParameter, passParameter);
        }
    }
}
