//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinTaiKhoan
    {
        public int id { get; set; }
        public int idkhoahoc { get; set; }
        public int idcapdo { get; set; }
        public int diemKN { get; set; }
        public Nullable<int> diemKNDay { get; set; }
        public Nullable<int> idbaihoc { get; set; }
        public int idtaikhoan { get; set; }
    
        public virtual CapDo CapDo { get; set; }
        public virtual DSBaiHoc DSBaiHoc { get; set; }
        public virtual KhoaHoc KhoaHoc { get; set; }
        public virtual LoaiDiemKN LoaiDiemKN { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
