//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinTaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongTinTaiKhoan()
        {
            this.DSBaiHocPass_Of_TaiKhoan = new HashSet<DSBaiHocPass_Of_TaiKhoan>();
            this.DSKhoaHocPass_Of_TaiKhoan = new HashSet<DSKhoaHocPass_Of_TaiKhoan>();
        }
    
        public int id { get; set; }
        public int idkhoahoc { get; set; }
        public int idcapdo { get; set; }
        public int diemKN { get; set; }
        public Nullable<int> diemKNDay { get; set; }
        public int idtaikhoan { get; set; }
        public Nullable<System.DateTime> ngayhoc { get; set; }
    
        public virtual CapDo CapDo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DSBaiHocPass_Of_TaiKhoan> DSBaiHocPass_Of_TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DSKhoaHocPass_Of_TaiKhoan> DSKhoaHocPass_Of_TaiKhoan { get; set; }
        public virtual KhoaHoc KhoaHoc { get; set; }
        public virtual LoaiDiemKN LoaiDiemKN { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
