USE [WebLapTrinh]
GO
UPDATE [dbo].[KhoaHoc] SET [tenkhoahoc] = N'Python', [imgKhoaHoc] = 'https://itviec.com/blog/wp-content/uploads/2017/06/tai-lieu-python.png' WHERE [id] = 8
UPDATE [dbo].[DSBaiHoc] SET [tenbaihoc] = N'Lập trình Python cơ bản' WHERE [id] = 11

SET IDENTITY_INSERT [dbo].[DSCauHoi] ON
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (1, N'Đâu là khai báo biến đúng trong javascript', 7, 1)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (2, N'Khai báo biến kiểu số thực', 7, 1)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (3, N'Để nối chuỗi sử dụng toán tử += hoặc +. <br><code>var chuoiA = "Web học lập trình "; <br>chuoiB = "thật bổ ích"</code>', 7, 1)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (4, N'Đâu là khai báo mảng đúng', 7, 1)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (5, N'Đối tượng được khai báo nhờ vào cập name:value và nằm trong { }', 7, 1)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (6, N'Mảng cars có 3 phần tử, đâu là cách truy cập phần tử đúng', 7, 2)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (7, N'<code>var x = 10; <br>var y = "20"; <br/>var z = x + y; <br></code> Kết quả nào sau đây là đúng', 7, 2)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (8, N'<code>var x = "100"; <br>var y = "10"; <br>var z = x - y;<br></code> Kết quả nào sau đây là đúng', 7, 2)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (9, N'<code>var x = 3;</code>. Đâu là phép so sánh cho ra kết quả là false', 7, 2)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (10, N'Đâu là phép so sánh cho kết quả là true', 7, 2)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (11, N'Car định nghĩa là 1 lớp, myCar là 1 đối tượng. Trong lớp Car có phương thức tĩnh hello. <br>Vậy đâu là sử dụng đúng phương thức tĩnh', 7, 3)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (12, N'Tầm vực: Phạm vi toàn cục và Phạm vi hàm', 7, 3)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (13, N'<code>var myStr = "Bob";<br>myStr[0] = "J";</code><br>. Đoạn code trên làm gì?', 7, 3)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (14, N'<code>var fruits = [ "Banana", "Orange", "Apple", "Mango" ];<br>fruits.<strong>______</strong> ;</code><br>Sử dụng phương thức nào để loại bỏ phần tử đầu tiên', 7, 3)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (15, N'<code>var myDog = { name": "Gâu Gâu", "legs": 4, "bark": "woof"}</code>. Để thêm một thuộc tính vào đối tượng, sử dụng cách nào dưới đây', 7, 3)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (16, N'Đâu là khai báo biến đúng trong PHP', 10, 1)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (17, N'<code>$xinChao = "Học lập trình thật vui";<br><strong>____</strong> $xinChao;</code>. Điền từ khóa in biến xinChao', 10, 1)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (18, N'Các kiểu dữ liệu hỗ trợ trong PHP', 10, 1)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (19, N'Dự đoán kết quả của đoạn code sau<br><code>$x = 100; <br>$y = "100";<br>var_dump($x === $y); </code>', 10, 1)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (20, N'Dự đoán kết quả của đoạn code sau<br><code>$x = 100; <br>$y = "100";<br>var_dump($x == $y); </code>', 10, 1)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (21, N'<code>function setHeight(int $minheight <strong>_____</strong>) {<br>&emsp;&emsp;echo "The height is : $minheight";<br>}</code>. PHP có tham số mặc định?', 10, 2)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (22, N'Các biến toàn cục có sẵn trong PHP bao gồm: ', 10, 2)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (23, N'Sử dụng phương thức tĩnh và thuộc tính tĩnh trong PHP', 10, 2)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (24, N'Để mở kết nối tới database trong PHP', 10, 2)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (25, N'<code>session_start();<br> <strong>_____</strong>["session"] = "green";</code><br>Tạo session trong PHP', 10, 2)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (26, N'<code>$myfile = fopen("webdictionary.txt", "<strong>__</strong>")</code><br>Yêu cầu chỉ đọc tập tin', 10, 3)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (27, N'<code>$myfile = fopen("webdictionary.txt", "<strong>__</strong>")</code><br>Yêu cầu đọc và ghi tập tin, bắt đầu từ đầu tập tin', 10, 3)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (28, N'<code>$cars = array("Volvo", "BMW", "Toyota");<br>echo <strong>_____</strong>($cars);</code><br>Hàm xử lý mảng thành JSON', 10, 3)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (29, N'<code>echo "Today is " . date("d/m/Y"); echo " Today is " . date("l");</code><br>Kết quả lần lượt là', 10, 3)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (30, N'Để viết script PHP cần khai báo?', 10, 3)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (31, N'Cú pháp để in ra "Hello World" trong Python?', 11, 1)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (32, N'Khai báo biến trong Python', 11, 1)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (33, N'Để lặp qua 1 dãy (list, dictionary, string, tuple) thì sử dụng lệnh nào dưới đây', 11, 1)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (34, N'Cú pháp khai báo hàm trong Python', 11, 1)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (35, N'Cú pháp đúng khai báo list trong Python', 11, 1)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (36, N'Cho 1 dictionaries như sau<br><code>d = dict([(''c'', 100), (''z'', -44)])</code><br>Tìm khóa c có trong dictionaries', 11, 2)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (37, N'Làm sao để viết câu điều kiện if <code>if <strong>____</strong> :</code>', 11, 2)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (38, N'Làm sao để viết vòng lặp for <code>for <strong>____</strong> : </code>', 11, 2)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (39, N'Câu lệnh nào dùng để dừng vòng lặp', 11, 2)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (40, N'Python là loại ngôn ngữ gì?', 11, 2)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (41, N'<code>f = open("demofile.txt", "<strong>__</strong>")</code><br>Làm sao đọc file text', 11, 3)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (42, N'<code>f = open("demofile.txt", "<strong>__</strong>")</code><br>Làm sao để ghi tiếp vào file text', 11, 3)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (43, N'<code>os.<strong>_____</strong>("demofile.txt")</code><br>Làm sao để xóa file', 11, 3)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (44, N'__init__() là hàm gì trong Python', 11, 3)
INSERT [dbo].[DSCauHoi] ([id], [tencauhoi], [idbaihoc], [idcapdo]) VALUES (45, N'Khai báo lambda trong Python?', 11, 3)
SET IDENTITY_INSERT [dbo].[DSCauHoi] OFF

INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (1, N'var tenBien;', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (1, N'int tenBien;', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (1, N'string tenBien;', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (1, N'float tenBien;', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (2, N'var soThuc = 5;', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (2, N'float soThuc = 16.5;', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (2, N'var soThuc = 5.6;', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (2, N'double soThuc = 10.45;', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (3, N'chuoiA -= chuoiB;', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (3, N'chuoiA += chuoiB;', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (3, N'chuoiA = chuoiB - chuoiB;', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (4, N'var cars = {"Saab", "Volvo", "BMW"};', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (4, N'var cars = new array("Saab", "Volvo", "BMW");', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (4, N'var cars = ["Saab", "Volvo", "BMW"];', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (5, N'var person = [name:"Michael", age:10, eyeColor:"black"];', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (5, N'var person = {name:"Peter", age, eyeColor:"black"};', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (5, N'var person = {name:"John"; age:20; eyeColor:"blue"};', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (5, N'var person = {name:"Terry", age:30, eyeColor:"blue"};', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (7, N'z = "1020" (là chuỗi)', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (7, N'z = 30 (là số', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (7, N'Sai syntax', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (8, N'z = "90" (là chuỗi)', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (8, N'z = 90 (là số)', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (8, N'Sai syntax', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (9, N'x === 3', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (9, N'x == "3"', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (9, N'x === "3"', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (10, N'"2" < "12"', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (10, N'"2" == "12"', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (10, N'"2" > "12"', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (10, N'2 > "John"', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (11, N'Car.hello();', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (11, N'mycar.hello();', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (12, N'Phạm vi toàn cục: là biến được khai báo bên trong hàm <br> Phạm vi hàm: là biến được khai báo bên ngoài hàm', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (12, N'Phạm vi toàn cục: là biến được khai báo bên ngoài hàm <br> Phạm vi hàm: là biến được khai báo bên trong hàm', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (12, N'Phạm vi toàn cục chỉ có thể truy cập bên trong hàm được khai báo', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (12, N'Phạm vi hàm có thể truy cập bất kỳ đâu trong chương trình', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (13, N'Truy cập phần tử đầu tiên và thay đổi ký tự B sang ký tự J', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (13, N'Truy cập phần tử đầu tiên nhưng vì giá trị là kiểu String nên không thể thay đổi ký tự', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (13, N'Sai cú pháp', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (14, N'shift()', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (14, N'pop()', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (14, N'unshift()', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (14, N'push()', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (15, N'myDog.owner = "John"', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (15, N'myDog.["owner"] = "John"', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (15, N'myDog.name = "Meo Meo"', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (15, N'Cả A và B', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (16, N'var x = 5', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (16, N'int x = 5', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (16, N'String x = "hello!"', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (16, N'$x = 5', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (17, N'$xinChao', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (17, N'echo $xinChao', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (17, N'print $xinChao', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (17, N'Cả B và C đúng', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (18, N'String, Integer, Float, Boolean, Object, NULL, Resource', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (18, N'String, Integer, Float, Boolean, Array, Object, NULL', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (18, N'String, Integer, Float, Boolean, Array, Object, NULL, Resource', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (18, N'String, Integer, Float, Double, Boolean, Array, Object, NULL, Resource', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (19, N'True', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (19, N'False', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (19, N'Lỗi cú pháp', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (20, N'True', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (20, N'False', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (20, N'Lỗi cú pháp', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (21, N'Không có giá trị mặc định', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (21, N' = 50.45', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (21, N' = 50', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (22, N'$GLOBALS, $_SERVER, $_REQUEST, $_POST, $_GET, $_FILES, $_ENV', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (22, N'$_REQUEST, $_POST, $_GET, $_FILES, $_ENV', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (22, N'$GLOBALS, $_SERVER, $_REQUEST, $_POST, $_GET, $_FILES, $_ENV, $_COOKIE, $_SESSION', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (22, N'$GLOBALS, $_SERVER, $_REQUEST, $_POST, $_GET, $PUT, $DELETE, $PATCH, $_FILES, $_ENV, $_COOKIE, $_SESSION', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (23, N'ClassName::staticMethod(); và ClassName::staticProp();', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (23, N'ClassName.staticMethod(); và ClassName.staticProp();', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (23, N'ClassName::staticMethod(); và ClassName.staticProp();', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (23, N'ClassName.staticMethod(); và ClassName::staticProp();', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (24, N'$conn = new mysqli($servername, $password, $username);', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (24, N'$conn = new mysqli($username, $servername, $password);', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (24, N'$conn = new mysqli($username, $password, $servername);', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (24, N'$conn = new mysqli($servername, $username, $password);', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (25, N'$SESSION', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (25, N'$_SESSION', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (25, N'$_COOKIE', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (25, N'$COOKIE', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (26, N'r+', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (26, N'r', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (26, N'a', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (26, N'x', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (27, N'w+', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (27, N'w', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (27, N'r+', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (27, N'a+', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (28, N'json_encode', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (28, N'json_decode', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (29, N'Today is 2019/12/09 Today is Monday', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (29, N'Today is Monday Today is 09/12/2019 ', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (29, N'Today is Monday Today is  2019/12/09', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (29, N'Today is 09/12/2019 Today is Monday', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (30, N'<?php ... ?>', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (30, N'<?php ... ?php>', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (30, N'<?php ... />', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (30, N'<?php .. /php>', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (31, N'echo("Hello world");', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (31, N'print("Hello world");', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (31, N'echo "Hello world"', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (31, N'print("Hello world")', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (32, N'x = int(5)', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (32, N'x = 5', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (32, N'Cả 2 đáp án trên', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (33, N'Lệnh while', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (33, N'Lệnh for', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (33, N'Cả 2 lệnh đều được', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (34, N'function inKetQua():', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (34, N'create inKetQua():', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (34, N'def inKetQua():', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (35, N'{"name": "banana", "color": "green"}', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (35, N'("apple", "banana", "cherry")', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (35, N'{"apple", "banana", "cherry"}', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (35, N'["apple", "banana", "cherry"]', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (36, N'Sử dụng for để tìm key có trong dictionaries', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (36, N'''c'' in d ', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (36, N'Cả 2 đáp án trên', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (37, N'(x > y)', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (37, N'x > y then', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (37, N'x > y', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (38, N'hocSinh => dsHocSinh', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (38, N'hocSinh in dsHocSinh', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (38, N'each hocSinh in dsHocSinh', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (39, N'stop', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (39, N'return', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (39, N'exit', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (39, N'break', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (40, N'Ngôn ngữ thông dịch (interpreted language)', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (40, N'Ngôn ngữ biên dịch (compiled language)', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (41, N'wt', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (41, N'rb', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (41, N'rt', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (41, N'ab', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (42, N'rb', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (42, N'xt', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (42, N'wb', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (42, N'at', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (43, N'delete', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (43, N'remove', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (43, N'deleteFile', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (43, N'removeFile', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (44, N'Không tồn tại cú pháp trên', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (44, N'Hàm khởi tạo của class', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (45, N'lambda arguments : expression. vd: lambda a : a * 10', 1)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (45, N'lambda arguments : return expression. vd: lambda a, n : return a * n', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (45, N'lambda arguments => expression. vd lambda a => a * 10', 0)
INSERT [dbo].[DSDapAn] ([idcauhoi], [cautraloi], [dapan]) VALUES (45, N'lambda arguments => return expression. vd lambda a, n => return a * n', 0)
